classify: 
  ["mans", "womens", "kids", "shoes", "bag", "family", 
          "fashionables", "sports", "summer", "winter"]

product_type: 
  ["Áo khoác", "Áo blazer", "Áo sơ mi", "Áo kiểu","Áo phông","Áo nỉ chui đầu",
                      "Áo polo", "Áo len", "Hàng dệt kim","Quần âu ","Quần bò","Chân váy",
                      "Denim","Quần Short","Bộ com lê","Trang phục đồng bộ","Đầm | Jumpsuit"]  
size:
  ["XS", "S", "M", "L","XL",
            "9-12-months-80_cm", "12-24-months-86_cm",
            "2-3-years-98_cm", "3-4 years-104_cm", "4-5-years_110_cm", 
            "6_years_116_cm", "7_years_122_cm", "8_years_128_cm", 
            "9_years_134_cm", "10_years_140_cm", "11-12_years_152_cm"]  
limit_product: 4                            


 


  

